name: redin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.10
  google_fonts: ^6.2.1
  http: ^1.3.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  test: ^1.25.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/redin_logo.png
    - assets/images/home/home_background.png

    - assets/images/roulette/ruleta.webp
    - assets/images/roulette/arrow.webp

    - assets/images/horse/rail.png
    - assets/images/horse/caballo_rojo.png
    - assets/images/horse/caballo_verde.png
    - assets/images/horse/caballo_azul.png
    - assets/images/horse/caballo_amarillo.png

    - assets/images/blackjack/table/card_thrower.webp
    - assets/images/blackjack/table/card_outline.webp
    - assets/images/blackjack/table/start_button.webp

    # Diamantes
    - assets/images/blackjack/cards/2_of_diamonds.webp
    - assets/images/blackjack/cards/3_of_diamonds.webp
    - assets/images/blackjack/cards/4_of_diamonds.webp
    - assets/images/blackjack/cards/5_of_diamonds.webp
    - assets/images/blackjack/cards/6_of_diamonds.webp
    - assets/images/blackjack/cards/7_of_diamonds.webp
    - assets/images/blackjack/cards/8_of_diamonds.webp
    - assets/images/blackjack/cards/9_of_diamonds.webp
    - assets/images/blackjack/cards/10_of_diamonds.webp
    - assets/images/blackjack/cards/jack_of_diamonds.webp
    - assets/images/blackjack/cards/queen_of_diamonds.webp
    - assets/images/blackjack/cards/king_of_diamonds.webp
    - assets/images/blackjack/cards/ace_of_diamonds.webp

    # Corazones
    - assets/images/blackjack/cards/2_of_hearts.webp
    - assets/images/blackjack/cards/3_of_hearts.webp
    - assets/images/blackjack/cards/4_of_hearts.webp
    - assets/images/blackjack/cards/5_of_hearts.webp
    - assets/images/blackjack/cards/6_of_hearts.webp
    - assets/images/blackjack/cards/7_of_hearts.webp
    - assets/images/blackjack/cards/8_of_hearts.webp
    - assets/images/blackjack/cards/9_of_hearts.webp
    - assets/images/blackjack/cards/10_of_hearts.webp
    - assets/images/blackjack/cards/jack_of_hearts.webp
    - assets/images/blackjack/cards/queen_of_hearts.webp
    - assets/images/blackjack/cards/king_of_hearts.webp
    - assets/images/blackjack/cards/ace_of_hearts.webp

    # Tr√©boles
    - assets/images/blackjack/cards/2_of_clubs.webp
    - assets/images/blackjack/cards/3_of_clubs.webp
    - assets/images/blackjack/cards/4_of_clubs.webp
    - assets/images/blackjack/cards/5_of_clubs.webp
    - assets/images/blackjack/cards/6_of_clubs.webp
    - assets/images/blackjack/cards/7_of_clubs.webp
    - assets/images/blackjack/cards/8_of_clubs.webp
    - assets/images/blackjack/cards/9_of_clubs.webp
    - assets/images/blackjack/cards/10_of_clubs.webp
    - assets/images/blackjack/cards/jack_of_clubs.webp
    - assets/images/blackjack/cards/queen_of_clubs.webp
    - assets/images/blackjack/cards/king_of_clubs.webp
    - assets/images/blackjack/cards/ace_of_clubs.webp

    # Picas
    - assets/images/blackjack/cards/2_of_spades.webp
    - assets/images/blackjack/cards/3_of_spades.webp
    - assets/images/blackjack/cards/4_of_spades.webp
    - assets/images/blackjack/cards/5_of_spades.webp
    - assets/images/blackjack/cards/6_of_spades.webp
    - assets/images/blackjack/cards/7_of_spades.webp
    - assets/images/blackjack/cards/8_of_spades.webp
    - assets/images/blackjack/cards/9_of_spades.webp
    - assets/images/blackjack/cards/10_of_spades.webp
    - assets/images/blackjack/cards/jack_of_spades.webp
    - assets/images/blackjack/cards/queen_of_spades.webp
    - assets/images/blackjack/cards/king_of_spades.webp
    - assets/images/blackjack/cards/ace_of_spades.webp

    - assets/images/blackjack/cards/Reverso.webp
    - assets/images/blackjack/blackjack_title.webp


    - assets/audio/casino.ogg
    - assets/audio/fail_sound.ogg
    - assets/audio/roulette/win.ogg
    - assets/audio/roulette/ball_sound.ogg
    - assets/audio/horse/horse_racing.ogg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/redin_icon.webp"